name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install JS dependencies
        run: npm ci

      - name: Format JS/TS
        run: npx prettier --write .

      - name: Lint TypeScript
        run: npm run lint

      - name: Run JS tests
        run: npm test

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal

      - name: Format Rust
        run: cargo fmt --all

      - name: Lint Rust
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Rust tests
        run: cargo test

      - name: Auto commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply auto formatting"
        if: github.event_name == 'push'
